apiVersion: serverless.keetle.io/v1alpha1
kind: Serverless
metadata:
  name: example-serverless
spec:
  hostname: reverse-words
  port: 9999
  in-flight-requests: 2
  scale-to-zero-grace-period: 15s
  podSpec:
    containers:
    - image: quay.io/famargon/quarkus-sample-app
      imagePullPolicy: Always
      name: quarkus-app
      env:
        - name:  deployment.environment
          value: kubernetes
        - name:  service.name
          value: quarkus-app-kubernetes
      livenessProbe:
        httpGet:
          path: /health
          port: 9999
          # httpHeaders:
          # - name: Custom-Header
          # value: Awesome
        initialDelaySeconds: 1
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /health
          port: 9999
          # httpHeaders:
          # - name: Custom-Header
          # value: Awesome
        initialDelaySeconds: 1
        periodSeconds: 2
      terminationGracePeriodSeconds: 15