apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serverlesses.serverless.keetle.io
  namespace: serverless-infra
spec:
  group: serverless.keetle.io
  names:
    kind: Serverless
    listKind: ServerlessList
    plural: serverlesses
    singular: serverless
    shortNames:
      - svl
      - svls
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
